name: Checks
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 8
          cache: 'yarn'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run ESLint
        run: yarn lint

  jest_tests:
    name: Run unit tests with Jest
    needs: [ code_quality ]
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 8
          cache: 'yarn'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run Jest
        run: yarn test

